ProjectMVC/ProjectMVC.UI/Controllers/AppUserController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using ProjectMVC.BLL.AppUserService;
using ProjectMVC.BLL.DTOs.AppUserDTOs;
using ProjectMVC.UI.Models.VMs.AppUserVMs;
using System.Security.Claims;

namespace ProjectMVC.UI.Controllers
{
    public class AppUserController : Controller
    {
        private readonly IAppUserService _appUserService;
        private readonly IMapper _mapper;

        public AppUserController(IAppUserService appUserservice, IMapper mapper)
        {
            _appUserService = appUserservice;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(RegisterVM addVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var user = _mapper.Map<RegisterDTO>(addVM);
                    var result = await _appUserService.Register(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Login");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description.ToString());
                        }
                    }
                }
                return View(addVM);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(addVM);
            }

        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginVM loginVM)
        {
            try
            {
                LoginDTO userdto = _mapper.Map<LoginDTO>(loginVM);

                if (userdto != null)
                {
                    var result = await _appUserService.Login(userdto);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index", "Article");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Hatalı giriş");
                    }
                }
                else
                {
                    ModelState.AddModelError("Kullanıcı bulunamadı", "Lütfen kayıt olunuz.");
                }

                return View(loginVM);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(loginVM);
            }

        }

        public async Task<IActionResult> LogOut()
        {
            await _appUserService.LogOut();
            return RedirectToAction("Index", "Article");
        }


        [HttpGet]
        public async Task<IActionResult> Update(string id)
        {
           
            var user = User.FindFirstValue(ClaimTypes.NameIdentifier);
            id = user;

            AppUserListDTO userDTO = await _appUserService.GetByIdAsync(id);

            if (userDTO == null)
            {
                return RedirectToAction("NotFound");
            }

            AppUserUpdateVM userUpdateVM = _mapper.Map<AppUserUpdateVM>(userDTO);
            return View(userUpdateVM);
        }

        [HttpPost]
        public async Task<IActionResult> Update(AppUserUpdateVM updateVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var userDTO = _mapper.Map<AppUserUpdateDTO>(updateVM);
                    var result = await _appUserService.Update(userDTO);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index", "Article");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                return View(updateVM);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(updateVM);
            }
            
        }
    }
}

ProjectMVC/ProjectMVC.UI/Controllers/SubjectController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using ProjectMVC.BLL.DTOs.SubjectDTOs;
using ProjectMVC.BLL.SubjectService;
using ProjectMVC.CORE.Concrete;
using ProjectMVC.UI.Models.VMs.SubjectVMs;

namespace ProjectMVC.UI.Controllers
{
    public class SubjectController : Controller
    {
        private readonly ISubjectService _subjectService;
        private readonly IMapper _mapper;

        public SubjectController(ISubjectService subjectService, IMapper mapper)
        {
            _subjectService = subjectService;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var subjects = await _subjectService.GetAllAsync();
            var subjectsVM = subjects.Select(x => _mapper.Map<SubjectListVM>(x)).ToList();
            return View(subjectsVM);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(SubjectCreateVM subjectCreateVM)
        {
            if (ModelState.IsValid)
            {
                SubjectCreateDTO subject = _mapper.Map<SubjectCreateDTO>(subjectCreateVM);
                await _subjectService.AddAsync(subject);
                return RedirectToAction("Index");
            }
            else
            {
                return View(subjectCreateVM);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            SubjectListDTO subject = await _subjectService.GetByIdAsync(id);
            if (subject == null)
            {
                return RedirectToAction("NotFound");
            }

            SubjectUpdateVM subjectUpdateVM = _mapper.Map<SubjectUpdateVM>(subject);
            return View(subjectUpdateVM);
        }


        [HttpPost]
        public IActionResult Update(SubjectUpdateVM subjectUpdateVM)
        {
            if (ModelState.IsValid)
            {
                SubjectUpdateDTO subject = _mapper.Map<SubjectUpdateDTO>(subjectUpdateVM);
                _subjectService.Update(subject);
                return RedirectToAction("Index");
            }
            else
            {
                return View(subjectUpdateVM);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int Id)
        {
            SubjectListDTO subjectDeleted = await _subjectService.GetByIdAsync(Id);
            Subject subjectDel = _mapper.Map<Subject>(subjectDeleted);

            await _subjectService.DeleteAsync(subjectDel.Id);
            return RedirectToAction("Index");

        }
    }
}

ProjectMVC/ProjectMVC.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectMVC.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjectMVC.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Article" asp-action="Index">ProjectMVC.UI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Subject" asp-action="Index">Konu</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="Index">Makaleler</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="Create">Makale Yaz</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="UserArticleList">Makalelerim</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AppUser" asp-action="Update">Ayarlar</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AppUser" asp-action="LogOut">Çıkış Yap</a>
                            </li>
                            <li class="nav-item text-end d-flex align-items-center">
                                Kullanıcı : @User.Identity.Name
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Subject" asp-action="Index">Konu</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="Index">Makale</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="Create">Makale Yaz</a>
                            </li>
                            
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AppUser" asp-action="Create">Kayıt Ol</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AppUser" asp-action="Login">Giriş Yap</a>
                            </li>
                        }
                    </ul>                                     

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ProjectMVC.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>